name: techs
description: "A new Flutter project."

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  dio: ^5.3.4
  html: ^0.15.4
  get_it: ^7.6.4

  #mobx part
  mobx: ^2.1.4
  flutter_mobx: ^2.0.6+5
  mobx_codegen: ^2.1.1
  build_runner: ^2.3.3


  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0


flutter:


  uses-material-design: true


