name: techs
description: "A new Flutter project."

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  dio: ^5.3.4
  html: ^0.15.4
  get_it: ^7.6.4

  #mobx part
  mobx: ^2.1.4
  flutter_mobx: ^2.0.6+5
  mobx_codegen: ^2.1.1
  build_runner: ^2.3.3

  provider: ^6.0.5

  xml2json: ^6.2.2
  json_serializable: ^6.6.1
  json_annotation: ^4.8.1

  cupertino_icons: ^1.0.2

  gap: ^3.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0


flutter:


  uses-material-design: true
  fonts:
  - family: Encode
    fonts:
      - asset: asset/font/encode/encode-black.ttf
        weight: 900
      - asset: asset/font/encode/encode-extra-bold.ttf
        weight: 800
      - asset: asset/font/encode/encode-bold.ttf
        weight: 700
      - asset: asset/font/encode/encode-semi-bold.ttf
        weight: 600
      - asset: asset/font/encode/encode-medium.ttf
        weight: 500
      - asset: asset/font/encode/encode-regular.ttf
        weight: 400
      - asset: asset/font/encode/encode-light.ttf
        weight: 300
      - asset: asset/font/encode/encode-thin.ttf
        weight: 200
      - asset: asset/font/encode/encode-extra-light.ttf
        weight: 100


